"""initial migration

Revision ID: 70bfc56c00eb
Revises: 
Create Date: 2026-08-21 16:29:56.376762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bfc56c00eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jobs',
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True)
    )

    op.execute(
        "UPDATE jobs SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL"
    )

    op.alter_column(
        'jobs',
        'created_at',
        nullable=False
    )
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('current_attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'current_attempt')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
